# OpenShift Template for NPS Agent
#
# Deploy with:
#   oc process -f benchmark.yaml \
#     -p NAMESPACE="$NAMESPACE" \
#     -p MLFLOW_TRACKING_URI="$MLFLOW_TRACKING_URI" \
#     -p MLFLOW_EXPERIMENT_NAME="$MLFLOW_EXPERIMENT_NAME" \
#     | oc apply -f -
#
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prompt-optimization-benchmark-template
parameters:
  - name: NAMESPACE
    description: Your OpenShift project name (e.g., prompt-optimization-benchmark)
    required: true
  - name: MLFLOW_TRACKING_URI
    description: Your MLflow URL (e.g., https://data-science-gateway.apps.<cluster>/mlflow/)
    required: true
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: prompt-optimization-benchmark
      namespace: ${NAMESPACE}
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/taagarwa-rh/prompt-optimizer-benchmark
          ref: main
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: python:3.12-ubi9
      output:
        to:
          kind: ImageStreamTag
          name: prompt-optimization-benchmark:latest
      triggers:
        - type: ConfigChange
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: prompt-optimization-benchmark
      namespace: ${NAMESPACE}
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: prompt-optimization-benchmark
      namespace: ${NAMESPACE}
      labels:
        app: prompt-optimization-benchmark
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 6
      template:
        spec:
          restartPolicy: "OnFailure"
          containers:
            - name: prompt-optimization-benchmark
              image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/prompt-optimization-benchmark:latest
              volumeMounts:
                - name: config
                  mountPath: config.yaml
                  readOnly: True
              env:
                - name: MLFLOW_TRACKING_URI
                  value: "${MLFLOW_TRACKING_URI}"
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
          volumes:
            - name: config
              configMap:
                name: prompt-optimization-benchmark-config

